```bash
#!/usr/bin/env bash

set -euo pipefail

RDS_TF_FILE="${RDS_TF_FILE:-terraform/rds.tf}"
DB_ENGINE="${DB_ENGINE:-postgres}"
ENGINE_VERSION="${ENGINE_VERSION:-16}"
ALLOCATED_STORAGE="${ALLOCATED_STORAGE:-20}"

require_cmd() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "ERROR: '$1' is required."
        exit 1
    }
}

for cmd in git terraform gh; do
    require_cmd "$cmd"
done

git rev-parse --show-toplevel >/dev/null 2>&1 || {
    echo "ERROR: Run this script inside a Git repository."
    exit 1
}

cd "$(git rev-parse --show-toplevel)"

mkdir -p "$(dirname "$RDS_TF_FILE")"
touch "$RDS_TF_FILE"

echo
echo "=========================================="
echo "       RDS Terraform PR Automation"
echo "=========================================="
echo

read -r -p "RDS name: " RDS_NAME

RDS_NAME="$(
    printf '%s' "$RDS_NAME" |
    tr '[:upper:]' '[:lower:]' |
    tr -cd 'a-z0-9-'
)"

if [[ -z "$RDS_NAME" ]]; then
    echo "ERROR: RDS name cannot be empty."
    exit 1
fi

if [[ "$RDS_NAME" == *prod* ]]; then
    DELETION_PROTECTION=true
    ENVIRONMENT="prod"
else
    DELETION_PROTECTION=false
    ENVIRONMENT="non-prod"
fi

echo
echo "Select RDS size:"
echo "1) db.t3.micro"
echo "2) db.t3.small"
echo "3) db.t3.medium"
echo "4) db.r6g.large"
echo "5) db.r6g.xlarge"
echo

read -r -p "Choice [1-5]: " SIZE

case "$SIZE" in
    1) INSTANCE_CLASS="db.t3.micro" ;;
    2) INSTANCE_CLASS="db.t3.small" ;;
    3) INSTANCE_CLASS="db.t3.medium" ;;
    4) INSTANCE_CLASS="db.r6g.large" ;;
    5) INSTANCE_CLASS="db.r6g.xlarge" ;;
    *)
        echo "ERROR: Invalid size."
        exit 1
        ;;
esac

RESOURCE_NAME="$(
    printf '%s' "$RDS_NAME" |
    tr '-' '_'
)"

if grep -q "resource \"aws_db_instance\" \"$RESOURCE_NAME\"" "$RDS_TF_FILE"; then
    echo
    echo "ERROR: Terraform resource '$RESOURCE_NAME' already exists."
    exit 1
fi

echo
echo "------------------------------------------"
echo "RDS name             : $RDS_NAME"
echo "Instance class       : $INSTANCE_CLASS"
echo "Environment          : $ENVIRONMENT"
echo "Deletion protection  : $DELETION_PROTECTION"
echo "Terraform file       : $RDS_TF_FILE"
echo "------------------------------------------"
echo

if [[ "$DELETION_PROTECTION" == true ]]; then
    echo "=========================================="
    echo "WARNING: PRODUCTION RDS DETECTED"
    echo "=========================================="
    echo
    echo "RDS name contains 'prod'."
    echo "Deletion protection will ALWAYS be enabled."
    echo

    read -r -p "Type PROD to continue: " PROD_CONFIRM

    if [[ "$PROD_CONFIRM" != "PROD" ]]; then
        echo "Production confirmation failed."
        echo "Cancelled."
        exit 1
    fi
fi

echo
read -r -p "Create Terraform change and GitHub PR? [y/N]: " CONFIRM

if [[ ! "${CONFIRM:-n}" =~ ^[yY]$ ]]; then
    echo "Cancelled."
    exit 0
fi

BRANCH="automation/add-rds-${RDS_NAME}-$(date +%Y%m%d%H%M%S)"

echo
echo "Creating branch:"
echo "$BRANCH"

git checkout -b "$BRANCH"

cat >> "$RDS_TF_FILE" <<EOF

# ------------------------------------------------------------
# RDS: $RDS_NAME
# Environment: $ENVIRONMENT
# Generated by scripts/add-rds.sh
# ------------------------------------------------------------

resource "aws_db_instance" "$RESOURCE_NAME" {
  identifier = "$RDS_NAME"

  engine = "$DB_ENGINE"
  engine_version = "$ENGINE_VERSION"

  instance_class = "$INSTANCE_CLASS"
  allocated_storage = $ALLOCATED_STORAGE
  storage_type = "gp3"

  deletion_protection = $DELETION_PROTECTION
  skip_final_snapshot = false

  tags = {
    Name = "$RDS_NAME"
    Environment = "$ENVIRONMENT"
    ManagedBy = "Terraform"
  }
}

EOF

echo
echo "Running terraform fmt..."
terraform fmt "$RDS_TF_FILE"

echo
echo "Running terraform init..."
terraform \
    -chdir="$(dirname "$RDS_TF_FILE")" \
    init \
    -backend=false

echo
echo "Running terraform validate..."
terraform \
    -chdir="$(dirname "$RDS_TF_FILE")" \
    validate

echo
echo "Terraform validation passed."

git add "$RDS_TF_FILE"

if git diff --cached --quiet; then
    echo "ERROR: No Terraform changes detected."
    exit 1
fi

echo
echo "Creating commit..."

git commit -m "feat(rds): add ${RDS_NAME}"

echo
echo "Pushing branch..."

git push -u origin "$BRANCH"

DEFAULT_BRANCH="$(
    git remote show origin |
    sed -n '/HEAD branch/s/.*: //p'
)"

DEFAULT_BRANCH="${DEFAULT_BRANCH:-main}"

echo
echo "Creating GitHub Pull Request..."

PR_BODY=$(cat <<EOF
## RDS Terraform Change

Automated RDS Terraform change generated by:

\`scripts/add-rds.sh\`

### Configuration

| Setting | Value |
|---|---|
| RDS | \`$RDS_NAME\` |
| Engine | \`$DB_ENGINE\` |
| Engine version | \`$ENGINE_VERSION\` |
| Instance class | \`$INSTANCE_CLASS\` |
| Environment | \`$ENVIRONMENT\` |
| Deletion protection | \`$DELETION_PROTECTION\` |

### Production Safety

The RDS name was checked for the string:

\`prod\`

If detected, deletion protection was automatically set to:

\`\`\`hcl
deletion_protection = true
\`\`\`

This value cannot be overridden by the interactive user.

### Validation

Terraform formatting and validation passed before creating this PR.

### Deployment

This script does not execute:

\`\`\`text
terraform apply
\`\`\`

Deployment remains controlled by the normal CI/CD pipeline.
EOF
)

gh pr create \
    --title "feat(rds): add ${RDS_NAME}" \
    --base "$DEFAULT_BRANCH" \
    --head "$BRANCH" \
    --body "$PR_BODY"

echo
echo "=========================================="
echo "SUCCESS"
echo "RDS Terraform change created."
echo "GitHub Pull Request created."
echo "=========================================="
```
